### PR TITLE
Fix claim

### LINKED ISSUE #33: MaxFreeTransactionSize result in issues of ClaimTransaction
https://github.com/neo-project/neo-plugins/blob/db04e756a64c149e86d117fe89879c72f319c7df/SimplePolicy/SimplePolicy/config.json#L5
It causes a problem for ClaimTransaction.  
For ClaimTransaction, people can't add network fee to it because it's set to zero, which means every ClaimTransaction is free transaction.(https://github.com/neo-project/neo/blob/7883e587a9448330d21669ebe748402871da3a50/neo/Network/P2P/Payloads/ClaimTransaction.cs#L16) Besides, the size of ClaimTransaction is usually larger than 1024. If we set MaxFreeTransactionSize to 1024, all ClaimTransaction will be influenced. If we make MaxFreeTransactionSize larger than 1024, then it's a meaningless configuration item. We get a paradox here.
Another thing is We can't prioritize ClaimTransaction anyway.
(https://github.com/neo-project/neo/blob/7883e587a9448330d21669ebe748402871da3a50/neo/Network/P2P/Payloads/Transaction.cs#L52)

### PR DESCRIPTION
**Pull request by shargon**
Fix for https://github.com/neo-project/neo-plugins/issues/33#issuecomment-445194586
Closes #33

### CODE REVIEW

File: SimplePolicy/Settings.cs [hunk 1]
```diff
@@ -13,16 +13,19 @@ internal class Settings
         public int MaxFreeTransactionSize { get; }
         public Fixed8 FeePerExtraByte { get; }
         public BlockedAccounts BlockedAccounts { get; }
+        public HashSet<TransactionType> HighPriorityTx { get; set; }
```
Comment (igormcoelho) [inline SimplePolicy/Settings.cs]: I recommend rename to `HighPriorityTxType` (everyone will understand it faster)

File: SimplePolicy/Settings.cs [hunk 2]
```diff
@@ -13,16 +13,19 @@ internal class Settings
...
-            this.MaxFreeTransactionSize = GetValueOrDefault(section.GetSection("MaxFreeTransactionSize"), 1024, p => int.Parse(p));
-            this.FeePerExtraByte = GetValueOrDefault(section.GetSection("FeePerExtraByte"), Fixed8.FromDecimal(0.00001M), p => Fixed8.Parse(p));
-            this.BlockedAccounts = new BlockedAccounts(section.GetSection("BlockedAccounts"));
+            MaxTransactionsPerBlock = GetValueOrDefault(section.GetSection("MaxTransactionsPerBlock"), 500, p => int.Parse(p));
+            MaxFreeTransactionsPerBlock = GetValueOrDefault(section.GetSection("MaxFreeTransactionsPerBlock"), 20, p => int.Parse(p));
+            MaxFreeTransactionSize = GetValueOrDefault(section.GetSection("MaxFreeTransactionSize"), 1024, p => int.Parse(p));
+            FeePerExtraByte = GetValueOrDefault(section.GetSection("FeePerExtraByte"), Fixed8.FromDecimal(0.00001M), p => Fixed8.Parse(p));
+            BlockedAccounts = new BlockedAccounts(section.GetSection("BlockedAccounts"));
+            HighPriorityTx = new HashSet<TransactionType>(section.GetSection("HighPriorityTx").GetChildren()
```
Comment (igormcoelho) [inline SimplePolicy/Settings.cs]: `HighPriorityTxType`

File: SimplePolicy/SimplePolicy/config.json [hunk 3]
```diff
@@ -4,9 +4,13 @@
     "MaxFreeTransactionsPerBlock": 20,
     "MaxFreeTransactionSize": 1024,
     "FeePerExtraByte": 0.00001,
+    "HighPriorityTx":
```
Comment (igormcoelho) [inline SimplePolicy/SimplePolicy/config.json]: `HighPriorityTxType`

File: SimplePolicy/SimplePolicyPlugin.cs [hunk 4]
```diff
@@ -93,7 +93,7 @@ void ILogPlugin.Log(string source, LogLevel level, string message)
         private bool VerifySizeLimits(Transaction tx)
         {
             // Not Allow free TX bigger than MaxFreeTransactionSize
-            if (tx.IsLowPriority && tx.Size > Settings.Default.MaxFreeTransactionSize) return false;
+            if (IsLowPriority(tx) && tx.Size > Settings.Default.MaxFreeTransactionSize) return false;
```
Comment (igormcoelho) [inline SimplePolicy/SimplePolicyPlugin.cs]: We have a small problem here Shargon. ClaimTx cannot be paid (and they are often bigger than 1024... so users cannot pay nor cannot pass this limit), so I suggest we create another section called `CannotPayTxType` (including `ClaimTransaction`), so if transaction cannot be paid, this MaxFreeTransactionSize should not be imposed.

File: SimplePolicy/SimplePolicy/config.json [hunk 5]
```diff
@@ -4,9 +4,13 @@
...
+    [
+        "ClaimTransaction"
+    ],
```
Comment (igormcoelho) [inline SimplePolicy/SimplePolicy/config.json]: Create: 
```json
"CannotPayTxType":
  [
        "ClaimTransaction"
 ],
```
(please see explanation below)

File: SimplePolicy/SimplePolicyPlugin.cs [hunk 6]
```diff
@@ -60,13 +60,13 @@ private static IEnumerable<Transaction> FilterForBlock_Policy2(IEnumerable<Trans
...
 
-            Transaction[] free = tx_list.Where(p => p.IsLowPriority)
+            Transaction[] free = tx_list.Where(p => IsLowPriority(p))
                 .OrderByDescending(p => p.NetworkFee / p.Size)
                 .ThenByDescending(p => p.NetworkFee)
                 .Take(Settings.Default.MaxFreeTransactionsPerBlock)
                 .ToArray();
 
-            Transaction[] non_free = tx_list.Where(p => !p.IsLowPriority)
+            Transaction[] non_free = tx_list.Where(p => !IsLowPriority(p))
```
Comment (igormcoelho) [inline SimplePolicy/SimplePolicyPlugin.cs]: Ok, ClaimTx will enter here because its not LowPriority, correct? This is the part Im trying to.test (but will only be able to finish tomorrow). If ClaimTx netfee is always zero, wouldnt it be sent forever to the end of the queue?
I guess Peter mentioned this situation... so if thats the case, we will need to insert it together with the free tx (20 maximum), with bigger priority than all other free tx, and not subject to maxfreetxsizelimit. Please confirm if Im mistaken here.

File: SimplePolicy/SimplePolicyPlugin.cs (hunk 4 above)
Comment (shargon) [reply SimplePolicy/SimplePolicyPlugin.cs]: We should be able to enable and disable this in the config, but yes

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/pull/510#discussion_r240027402

**Comment by igormcoelho** [comment]
@shargon @erikzhang I think we need to improve this... right now, no ClaimTransaction will be selected if there are 480 paid transactions and 20 free. Look that free will be selected anyway, and Claim will not: https://github.com/neo-project/neo-plugins/pull/34/commits/61ea758b834638fcf1cd6b1b1ec43274fffc7915#diff-4ee5cc7d1c15c503f790e31380335bebR107

**Comment by shargon** [comment]
I have troubles with the last nuget package

image

**Comment by igormcoelho** [comment]
This is Neo package, no ? haha I changed it locally to the latest commit, to make it work, but I guess  we need a new version on Neo project.

**Comment by erikzhang** [comment]
@igormcoelho @shargon Please review.

**Comment by erikzhang** [comment]
@shargon You need to add NuGet package source in vs.

https://www.myget.org/F/neo/api/v3/index.json

image

**Comment by igormcoelho** [comment]
Do you think we could change logic to:

 .OrderByDescending(p => InHighPriorityList(p))  .ThenByDescending(p => p.NetworkFee / p.Size)
		                .ThenByDescending(p => p.NetworkFee)

This would put HighPriority on top.

File: SimplePolicy.UnitTests/SimplePolicy.UnitTests.csproj [hunk 7]
```diff
@@ -8,10 +8,17 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <PackageReference Include="FluentAssertions" Version="4.19.4" />
-    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
-    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
-    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
+    <None Update="protocol.json">
+      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
+    </None>
```
Comment (igormcoelho) [inline SimplePolicy.UnitTests/SimplePolicy.UnitTests.csproj]: This looks nice! Gives access to more information, very good.

File: SimplePolicy.UnitTests/UT_SimplePolicy.cs [hunk 8]
```diff
@@ -22,5 +30,225 @@ public void TestMaxTransactionsPerBlock()
...
+            vx = filteredTxList.Where(tx => tx.Type == TransactionType.ClaimTransaction);
+            vx.Count().Should().Be(4);
+
+            // =================================================================
+
+            // insert more invocation transactions (400 of each)
+            for (var i = 0; i < 400; i++)
+            {
+                TxList.Insert(0, MockGenerateInvocationTransaction(Fixed8.One, 50).Object);
+                TxList.Insert(0, MockGenerateInvocationTransaction(Fixed8.Zero, 50).Object);
```
Comment (igormcoelho) [inline SimplePolicy.UnitTests/UT_SimplePolicy.cs]: It could be an issue Erik (I'll verify updated ordering), if Claim is "HighPriority", it needs to gain from other low priority (even if other is 0.0009). As it is now it's testing only if it gains from Zero fee tx, so there will be no real priority.

File: SimplePolicy/SimplePolicyPlugin.cs [hunk 9]
```diff
@@ -63,6 +63,7 @@ private static IEnumerable<Transaction> FilterForBlock_Policy2(IEnumerable<Trans
             Transaction[] free = tx_list.Where(p => p.IsLowPriority)
                 .OrderByDescending(p => p.NetworkFee / p.Size)
                 .ThenByDescending(p => p.NetworkFee)
+                .ThenByDescending(p => InHighPriorityList(p))
```
Comment (igormcoelho) [inline SimplePolicy/SimplePolicyPlugin.cs]: I think NetworkFee / Size will always put Claim as last, because Fee is zero. Claim will only get "priority" if other low priority is zero (if everyone sends 0.0000001) no one will ever be able to claim.

Do you think we could change logic to (for free tx):

.OrderByDescending(p => InHighPriorityList(p)) .ThenByDescending(p => p.NetworkFee / p.Size)
.ThenByDescending(p => p.NetworkFee)

This would put HighPriority on top.

**Comment by igormcoelho** [comment]
The current sort with 30 LowPriority (where 4 have zero fee) tx + 4 claim tx:
```
sort1 tx 0 feeperbyte: 0.00009 netfee: 0.0009 priority: False
 sort1 tx 1 feeperbyte: 0.00008 netfee: 0.0008 priority: False
 sort1 tx 2 feeperbyte: 0.00007 netfee: 0.0007 priority: False
 sort1 tx 3 feeperbyte: 0.00006 netfee: 0.0009 priority: False
 sort1 tx 4 feeperbyte: 0.00006 netfee: 0.0006 priority: False
 sort1 tx 5 feeperbyte: 0.00005333 netfee: 0.0008 priority: False
 sort1 tx 6 feeperbyte: 0.00005 netfee: 0.0005 priority: False
 sort1 tx 7 feeperbyte: 0.00004666 netfee: 0.0007 priority: False
 sort1 tx 8 feeperbyte: 0.000045 netfee: 0.0009 priority: False
 sort1 tx 9 feeperbyte: 0.00004 netfee: 0.0008 priority: False
 sort1 tx 10 feeperbyte: 0.00004 netfee: 0.0006 priority: False
 sort1 tx 11 feeperbyte: 0.00004 netfee: 0.0004 priority: False
 sort1 tx 12 feeperbyte: 0.000035 netfee: 0.0007 priority: False
 sort1 tx 13 feeperbyte: 0.00003333 netfee: 0.0005 priority: False
 sort1 tx 14 feeperbyte: 0.00003 netfee: 0.0006 priority: False
 sort1 tx 15 feeperbyte: 0.00003 netfee: 0.0003 priority: False
 sort1 tx 16 feeperbyte: 0.00002666 netfee: 0.0004 priority: False
 sort1 tx 17 feeperbyte: 0.000025 netfee: 0.0005 priority: False
 sort1 tx 18 feeperbyte: 0.00002 netfee: 0.0004 priority: False
 sort1 tx 19 feeperbyte: 0.00002 netfee: 0.0003 priority: False
 sort1 tx 20 feeperbyte: 0.00002 netfee: 0.0002 priority: False
 sort1 tx 21 feeperbyte: 0.000015 netfee: 0.0003 priority: False
 sort1 tx 22 feeperbyte: 0.00001333 netfee: 0.0002 priority: False
 sort1 tx 23 feeperbyte: 0.00001 netfee: 0.0002 priority: False
 sort1 tx 24 feeperbyte: 0.00001 netfee: 0.0001 priority: False
 sort1 tx 25 feeperbyte: 0.00000666 netfee: 0.0001 priority: False
 sort1 tx 26 feeperbyte: 0.000005 netfee: 0.0001 priority: False
 sort1 tx 27 feeperbyte: 0 netfee: 0 priority: True
 sort1 tx 28 feeperbyte: 0 netfee: 0 priority: True
 sort1 tx 29 feeperbyte: 0 netfee: 0 priority: True
 sort1 tx 30 feeperbyte: 0 netfee: 0 priority: True
 sort1 tx 31 feeperbyte: 0 netfee: 0 priority: False
 sort1 tx 32 feeperbyte: 0 netfee: 0 priority: False
 sort1 tx 33 feeperbyte: 0 netfee: 0 priority: False
```
This reinforces that priority is also being given in the end of the list.

The proposed change (IsPriority first) generates the following sequence:
```
sort2 tx 0 feeperbyte: 0 netfee: 0 priority: True
 sort2 tx 1 feeperbyte: 0 netfee: 0 priority: True
 sort2 tx 2 feeperbyte: 0 netfee: 0 priority: True
 sort2 tx 3 feeperbyte: 0 netfee: 0 priority: True
 sort2 tx 4 feeperbyte: 0.00009 netfee: 0.0009 priority: False
 sort2 tx 5 feeperbyte: 0.00008 netfee: 0.0008 priority: False
 sort2 tx 6 feeperbyte: 0.00007 netfee: 0.0007 priority: False
 sort2 tx 7 feeperbyte: 0.00006 netfee: 0.0009 priority: False
 sort2 tx 8 feeperbyte: 0.00006 netfee: 0.0006 priority: False
 sort2 tx 9 feeperbyte: 0.00005333 netfee: 0.0008 priority: False
 sort2 tx 10 feeperbyte: 0.00005 netfee: 0.0005 priority: False
 sort2 tx 11 feeperbyte: 0.00004666 netfee: 0.0007 priority: False
 sort2 tx 12 feeperbyte: 0.000045 netfee: 0.0009 priority: False
 sort2 tx 13 feeperbyte: 0.00004 netfee: 0.0008 priority: False
 sort2 tx 14 feeperbyte: 0.00004 netfee: 0.0006 priority: False
 sort2 tx 15 feeperbyte: 0.00004 netfee: 0.0004 priority: False
 sort2 tx 16 feeperbyte: 0.000035 netfee: 0.0007 priority: False
 sort2 tx 17 feeperbyte: 0.00003333 netfee: 0.0005 priority: False
 sort2 tx 18 feeperbyte: 0.00003 netfee: 0.0006 priority: False
 sort2 tx 19 feeperbyte: 0.00003 netfee: 0.0003 priority: False
 sort2 tx 20 feeperbyte: 0.00002666 netfee: 0.0004 priority: False
 sort2 tx 21 feeperbyte: 0.000025 netfee: 0.0005 priority: False
 sort2 tx 22 feeperbyte: 0.00002 netfee: 0.0004 priority: False
 sort2 tx 23 feeperbyte: 0.00002 netfee: 0.0003 priority: False
 sort2 tx 24 feeperbyte: 0.00002 netfee: 0.0002 priority: False
 sort2 tx 25 feeperbyte: 0.000015 netfee: 0.0003 priority: False
 sort2 tx 26 feeperbyte: 0.00001333 netfee: 0.0002 priority: False
 sort2 tx 27 feeperbyte: 0.00001 netfee: 0.0002 priority: False
 sort2 tx 28 feeperbyte: 0.00001 netfee: 0.0001 priority: False
 sort2 tx 29 feeperbyte: 0.00000666 netfee: 0.0001 priority: False
 sort2 tx 30 feeperbyte: 0.000005 netfee: 0.0001 priority: False
 sort2 tx 31 feeperbyte: 0 netfee: 0 priority: False
 sort2 tx 32 feeperbyte: 0 netfee: 0 priority: False
 sort2 tx 33 feeperbyte: 0 netfee: 0 priority: False
```

File: SimplePolicy.UnitTests/UT_SimplePolicy.cs (hunk 8 above)
Comment (igormcoelho) [reply SimplePolicy.UnitTests/UT_SimplePolicy.cs]: Ok now, I remake the tests in a way that some Claims will pass and others will not pass.

File: SimplePolicy/SimplePolicyPlugin.cs (hunk 9 above)
Comment (igormcoelho) [reply SimplePolicy/SimplePolicyPlugin.cs]: As discussed, best ordering is the one proposed by Erik:
.OrderByDescending(p => p.NetworkFee / p.Size)
.ThenByDescending(p => p.NetworkFee)
.ThenByDescending(p => InHighPriorityList(p))

**Comment by igormcoelho** [comment]
Ok @shargon @erikzhang @PeterLinX this is nice to me. The discussions were important to clarify the sorting algorithm (thanks @vncoelho too), so new tests were included to make it easier for future reviews of the code.

File: SimplePolicy/SimplePolicyPlugin.cs (hunk 9 above)
Comment (jsolman) [reply SimplePolicy/SimplePolicyPlugin.cs]: I’ll need to make a change like this in my PR for improving large MemoryPool behavior, or it won’t necessarily reverify claim transactions ahead of other free transactions.
