### PR TITLE
Fix/memory

### LINKED ISSUE #129: Export block makes extremely high cost of memory which usually cause system killed on Linux.
Export block makes extremely high cost of memory which usually cause system killed on Linux.
On mainnet export, our server which has 16G memory, is only able to hold on  about 2 million blocks' export. After that, it's been killed by ubuntu. Here's the line graph. I think ImportBlocks plugin is necessary to improve algorithm for export.
image

### PR DESCRIPTION
**Pull request by KickSeason**
fix #129

### CODE REVIEW

**Comment by vncoelho** [comment]
Looks good idea.

**Comment by KickSeason** [comment]
@shargon  I will.

File: ImportBlocks/ImportBlocks.cs [hunk 1]
```diff
@@ -48,8 +48,9 @@ private bool OnExport(string[] args)
                     if (start <= end)
                         fs.Write(BitConverter.GetBytes(count), 0, sizeof(uint));
                     fs.Seek(0, SeekOrigin.End);
-                    using (Snapshot snapshot = Blockchain.Singleton.GetSnapshot())
-                        for (uint i = start; i <= end; i++)
+                    for (uint i = start; i <= end; i++)
+                    {
+                        using (Snapshot snapshot = Blockchain.Singleton.GetSnapshot())
```
Comment (erikzhang) [inline ImportBlocks/ImportBlocks.cs]: I think that create new snapshot each time is not a good idea. We can use `Blockchain.Singleton.Store.GetBlock()`. It won't create any snapshot and read block from inner database directly.

Comment (shargon) [reply ImportBlocks/ImportBlocks.cs]: Maybe use the `store` directly in order to prevent the cache? or something for disable the cache of the objects in the snapshots?

Comment (shargon) [reply ImportBlocks/ImportBlocks.cs]: Yes, is better directly with the `Store`

Comment (erikzhang) [reply ImportBlocks/ImportBlocks.cs]: It won't increase the memory, because they will be released by GC. You can test it.

Comment (shargon) [reply ImportBlocks/ImportBlocks.cs]: But is stored in the internal `dictionary`, so we will have the same problem, we need 
```csharp
public TValue TryGet(TKey key, bool cache=true)
```

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: So does `[]` operation,

File: ImportBlocks/ImportBlocks.cs [hunk 2]
```diff
@@ -42,57 +33,65 @@ private bool OnExport(string[] args)
...
+        }
+
+        private bool OnExport(string[] args)
+        {
+            bool writeStart;
+            uint start, count;
+            string path;
+            if (args.Length < 2) return false;
+            if (!string.Equals(args[1], "block", StringComparison.OrdinalIgnoreCase)
+                && !string.Equals(args[1], "blocks", StringComparison.OrdinalIgnoreCase))
```
Comment (shargon) [inline ImportBlocks/ImportBlocks.cs]: seems duplicated

File: ImportBlocks/ImportBlocks.cs (hunk 1 above)
Comment (erikzhang) [reply ImportBlocks/ImportBlocks.cs]: No. I'm **SURE** it will be released by GC automatically.

Comment (erikzhang) [reply ImportBlocks/ImportBlocks.cs]: https://github.com/neo-project/neo/blob/197a6ec216fe9ef2d17ac20f8ec6d95ed01fb1c3/neo/Persistence/Store.cs#L9

```c#
DataCache<UInt256, TrimmedBlock> IPersistence.Blocks => GetBlocks();
```

You can see the `=>`.

And https://github.com/neo-project/neo/blob/197a6ec216fe9ef2d17ac20f8ec6d95ed01fb1c3/neo/Persistence/LevelDB/LevelDBStore.cs#L44-L47

```c#
public override DataCache<UInt256, TrimmedBlock> GetBlocks()
{
    return new DbCache<UInt256, TrimmedBlock>(db, null, null, Prefixes.DATA_Block);
}
```

File: ImportBlocks/ImportBlocks.cs (hunk 2 above)
Comment (erikzhang) [reply ImportBlocks/ImportBlocks.cs]: What is this refactor?

File: ImportBlocks/ImportBlocks.cs [hunk 3]
```diff
@@ -17,23 +17,14 @@ public override void Configure()
             Settings.Load(GetConfiguration());
         }
 
-        private bool OnExport(string[] args)
```
Comment (vncoelho) [inline ImportBlocks/ImportBlocks.cs]: maybe keep the `OnExport` function declaration before `WriteBlocks`.

File: ImportBlocks/ImportBlocks.cs [hunk 4]
```diff
@@ -17,23 +17,14 @@ public override void Configure()
...
+        private void WriteBlocks(uint start, uint count, string path, bool writeStart)
         {
-            if (args.Length < 2) return false;
-            if (!string.Equals(args[1], "block", StringComparison.OrdinalIgnoreCase)
-                && !string.Equals(args[1], "blocks", StringComparison.OrdinalIgnoreCase))
-                return false;
-            if (args.Length >= 3 && uint.TryParse(args[2], out uint start))
+            uint end = start + count - 1;
+            using (FileStream fs = new FileStream(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None, 4096, FileOptions.WriteThrough))
```
Comment (vncoelho) [inline ImportBlocks/ImportBlocks.cs]: Can you add a comment on these options?

File: ImportBlocks/ImportBlocks.cs [hunk 5]
```diff
@@ -42,54 +33,65 @@ private bool OnExport(string[] args)
                         fs.Seek(sizeof(uint), SeekOrigin.Begin);
                     }
                     else
+                    {
+                        byte[] buffer = new byte[sizeof(uint)];
```
Comment (vncoelho) [inline ImportBlocks/ImportBlocks.cs]: Maybe declare `buffer` outside this `if else`

File: ImportBlocks/ImportBlocks.cs (hunk 2 above)
Comment (shargon) [reply ImportBlocks/ImportBlocks.cs]: I told him that both conditions `if/else` was very similar, so i asked him to join this two logics in only one

File: ImportBlocks/ImportBlocks.cs (hunk 3 above)
Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: will do

File: ImportBlocks/ImportBlocks.cs (hunk 5 above)
Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: will do

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: will do

File: ImportBlocks/ImportBlocks.cs (hunk 1 above)
Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: I will  try and test.

File: ImportBlocks/ImportBlocks.cs (hunk 2 above)
Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: This is not duplicated. I think this is to make `export` support `export blocks` and `export block`

File: ImportBlocks/ImportBlocks.cs (hunk 4 above)
Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: * `FileOption.WriteThrough` indicates that the system should write through any intermediate cache and go directly to disk.
* `4096` is the default size of `buffer`.

**Comment by KickSeason** [comment]
@erikzhang @vncoelho I update.

**Comment by erikzhang** [comment]
I don't understand why we have to refactor it?

**Comment by shargon** [comment]
The code is easier to maintain if is unified, the logic between was very similar.

File: ImportBlocks/ImportBlocks.cs [hunk 6]
```diff
@@ -19,79 +20,83 @@ public override void Configure()
...
-                        {
-                            Block block = snapshot.GetBlock(i);
-                            byte[] array = block.ToArray();
-                            fs.Write(BitConverter.GetBytes(array.Length), 0, sizeof(int));
-                            fs.Write(array, 0, array.Length);
-                            Console.SetCursorPosition(0, Console.CursorTop);
-                            Console.Write($"[{i}/{end}]");
-                        }
+                    {
+                        DataCache<UInt256, BlockState> blocks = Blockchain.Singleton.Store.GetBlocks();
```
Comment (shargon) [inline ImportBlocks/ImportBlocks.cs]: This doesn't compile in my branch
```suggestion
                        DataCache<UInt256, TrimmedBlock> blocks = Blockchain.Singleton.Store.GetBlocks();
```

File: ImportBlocks/ImportBlocks.cs [hunk 7]
```diff
@@ -19,79 +20,83 @@ public override void Configure()
...
+                        DataCache<UInt256, TransactionState> transactions = Blockchain.Singleton.Store.GetTransactions();
+                        UInt256 hash = Blockchain.Singleton.GetBlockHash(i);
+                        Block block = blocks.TryGet(hash).TrimmedBlock.GetBlock(transactions);
```
Comment (shargon) [inline ImportBlocks/ImportBlocks.cs]: Same here:

```suggestion
                        Block block = blocks.TryGet(hash).GetBlock(transactions);
```

File: ImportBlocks/ImportBlocks.cs [hunk 8]
```diff
@@ -19,79 +20,83 @@ public override void Configure()
...
-                    if (start <= end)
-                        fs.Write(BitConverter.GetBytes(count), 0, sizeof(uint));
-                    fs.Seek(0, SeekOrigin.End);
+                }
+                if (start <= end)
+                    fs.Write(BitConverter.GetBytes(count), 0, sizeof(uint));
+                fs.Seek(0, SeekOrigin.End);
+                for (uint i = start; i <= end; i++)
+                {
                     using (Snapshot snapshot = Blockchain.Singleton.GetSnapshot())
```
Comment (shargon) [inline ImportBlocks/ImportBlocks.cs]: Snapshot is not used

File: ImportBlocks/ImportBlocks.cs (hunk 1 above)
Comment (shargon) [reply ImportBlocks/ImportBlocks.cs]: It will be disposed if we call `GetBlocks();` inside the for.

**Comment by KickSeason** [comment]
Much cleaner now. Thanks @shargon .

**Comment by shargon** [comment]
The code looks good to me, @superboyiii could you test it if this solve the issue?

**Comment by KickSeason** [comment]
@nicolegys is testing.

File: ImportBlocks/ImportBlocks.cs [hunk 9]
```diff
@@ -19,79 +19,80 @@ public override void Configure()
...
+                }
+                if (start <= end)
+                    fs.Write(BitConverter.GetBytes(count), 0, sizeof(uint));
+                fs.Seek(0, SeekOrigin.End);
+                for (uint i = start; i <= end; i++)
+                {
+                    var blocks = Blockchain.Singleton.Store.GetBlocks();
+                    var transactions = Blockchain.Singleton.Store.GetTransactions();
+                    UInt256 hash = Blockchain.Singleton.GetBlockHash(i);
+                    Block block = blocks.TryGet(hash).GetBlock(transactions);
```
Comment (erikzhang) [inline ImportBlocks/ImportBlocks.cs]: There is no difference between this way and `Blockchain.Singleton.Store.GetBlock()`.

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: Different.
`GetBlock()`  
https://github.com/neo-project/neo/blob/e1fdde307153879f0a7ae64bd3e11d042284896e/neo/Persistence/Helper.cs#L31
`GetBlocks()`  
https://github.com/neo-project/neo/blob/e1fdde307153879f0a7ae64bd3e11d042284896e/neo/Persistence/LevelDB/LevelDBStore.cs#L46

Comment (erikzhang) [reply ImportBlocks/ImportBlocks.cs]: I mean:

```c#
var blocks = Blockchain.Singleton.Store.GetBlocks();
var transactions = Blockchain.Singleton.Store.GetTransactions();
UInt256 hash = Blockchain.Singleton.GetBlockHash(i);
Block block = blocks.TryGet(hash).GetBlock(transactions);
```

```c#
Blockchain.Singleton.Store.GetBlock(i);
```

There is no difference between these two ways.

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: This is Store.GetBlock(index)
```
public static Block GetBlock(this IPersistence persistence, uint index)
 {
       if (index == 0) return Blockchain.GenesisBlock;
       UInt256 hash = Blockchain.Singleton.GetBlockHash(index);
       if (hash == null) return null;
       return persistence.GetBlock(hash);
 }
```
It call GetBlock(hash)
```
public static Block GetBlock(this IPersistence persistence, UInt256 hash)
 {
            TrimmedBlock state = persistence.Blocks.TryGet(hash);
            if (state == null) return null;
            if (!state.IsBlock) return null;
            return state.GetBlock(persistence.Transactions);
 }
```
Which get block from `Blocks` cache and transactions from `Transactions` cache, not new cache.
We need get block from new cache every time.

Comment (erikzhang) [reply ImportBlocks/ImportBlocks.cs]: They are the same. You can test it.

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: Will test.

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: Oh! yes. 
`DataCache<UInt256, BlockState> IPersistence.Blocks => GetBlocks();`
You told me. Didn't get it. Anyway let me have a test.
Will make a new commit.

Comment (KickSeason) [reply ImportBlocks/ImportBlocks.cs]: 🙏dalao

**Comment by KickSeason** [comment]
I think we can merge now finally.

**Comment by superboyiii** [comment]
> The code looks good to me, @superboyiii could you test it if this solve the issue?

Nicole's result shows it works effectively and greatly reduces time and memory consume.

**Comment by nicolegys** [comment]
Good performance!
It took about 3h to export the mainnet blocks. 
Here are the monitoring records of cpu and memory.
